adam = "Adán"
adolph = "Adolfo"
adrien = "Adrian"
allen = "Alano"
albert = "Alberto"
alexander = "Alejandro"
alfred = "Alfredo"
alphonso = { common = "Alfonso", other = "Alonso" }
andrew = "Andres"
anthony = "Antonio"
arthur = "Arturo"
bartholomew = "Bartolomá"
bartrand = "Beltrán"
benedict = "Benito"
bernard = "Bernardo"
charles = "Carlos"
caesar = "Cesar"
cyrus = "Círo"
clement = "Clemente"
conrad = "Conrado"
cornelius = "Cornelio"
christopher = "Cristóbal"
daniel = "Daniel"
david = { common = "Davin", other = "Davis" }
dominic = "Domingo"
edmund = "Edmundo"
edward = "Eduardo"
henry = "Enrique"
ernest = "Ernesto"
stephan = "Esteban"
eugene = "Eugenio"
frederick = "Federico"
philip = "Felipe"
ferdinand = "Fernando"
frank = "Francisco"
gabriel = "Gabriel"
geoffrey = = "Geofredo"
gerald = "Gerardo"
gilbert = "Gilberto"
gregory = "Gregorio"
walter = "Gualterio"
william = "Guillermo"
harold = "Haroldo"
herbert = "Heberto"
horace = "Horacio"
hubert = "Huberto"
hugo = "Hugo"
angel = "Angel"
dingo = "Dingo"
gonzalo = "Gonzalo"
humphrey = "Hunfredo"
alphonso = "Ildefonso"
james = "Jaime"
george = "Jorge"
joseph = { common = "José", other = "Pepe" }
john = "Juan"
julius = "Julio"
leon = "León"
leonard = "Leonardo"
leopold = "Leopoldo"
lucas = "Lucas"
louis = "Luis"
manuel = "Manuel"
marcel = "Marcelo"
mark = "Marcos"
mario = "Mario"
martin = "Martín"
matthew = "Mateo"
michael = "Miguel"
nathan = "Natán"
oliver = "Olivario"
oscar = "Oscar"
osmond = "Osmundo"
paul = "Pablo"
frank = { common = "Pancho", other = "Paco" }
patrick = "Patricio"
peter = "Pedro"
rafael = "Rafael"
raymond = "Ramón"
raul = "Raul"
richard = "Ricardo"
robert = "Roberto"
rudolph = "Rodolfo"
roland = "Rolando"
rueben = "Ruben"
rupert = "Ruperto"
silvan = "Silvano"
silvester = "Silvestre"
theodore = "Teodoro"
timothy = "Timoteo"
thomas = "Tomás"
vincent = { common = "Vicente", other = "Victor" }
lorenzo = "Lorenzo"
nicholas = "Nicolás"
salvador = "Salvador"
samuel = "Samuel"
sancho = "Sancho"
santiago = "Santiago"
sergio = "Sergio"
adele = "Adela"
dawn = "Alba"
alice = "Alicia"
amy = "Amata"
ann = "Ana"
beatrice = "beatriz"
bridget = "Brigida"
camilla = "Camila"
carla = "Carla"
charlotte = "Carlota"
caroline = "Carolina"
carmen = "Carmen"
katherine = "Catalina"
constance = "Constancia"
christina = "Christina"
dorothy = "Dorotes"
helen = "Elena"
elsie = "Elisa"
emily = "Emilia"
grace = "Engracia"
henrietta = "Enriqueta"
estelle = "Estela"
esther = "Ester"
eugenia = "Eugenia"
eva = "Eva"
philippa = "Felipa"
florence = "Florencia"
frances = "Francisca"
gertrude = "Gertrudis"
gloria = "Gloria"
guadalupe = "Guadalupe"
wilhelmina = "Guillermina"
agnes = "Inés"
elizabeth = "Isabel"
josephine = { common = "Josefa", other = "josefina" }
jane = "Juana"
juliet = "Julieta"
laura = "Laura"
eleanor = "Leonor"
leticia = "Leticia"
dolores = { common = "Dolores", nickname = "Lola" }
lucy = "Lucía"
louise = "Luisa"
emma = "Manuela"
margaret = "Margarita"
mary = "María"
marian = "Mariana"
martha = "Marta"
hortense = "Ortensia"
patricia = "Patricia"
pauline = "Paula"
pearl = "Perla"
pilar = "Pilar"
ramona = "Ramona"
rachel = "Raquel"
rose = { common = "Rosario", nickname = ["Rosa", "Rosita"] }
sophie = "Sofia"
susan = { common = "Soledad", other = "Susann" }
theodora = "Teodora"
therese = "Teresa"
victoria = "Victoria"
virginia = "Virginia"
diana = "Diana"
sarah = "Sara"
amalia = "Amalia"
gabriela = { common = "Gabriela", nickname = "Gabi" }
julia = "Julia"
marcela = "Marcela"
maricarmen = "Maricarmen"
mercedes = "Mercedes"
monica = "Monica"
rebecca = "Rebeca"
yolanda = { common = "Yolanda", nickname = "Yoli" }
tina = "Tina"
