# Universal Text Encoding as Meaning                                           #
# Copyright (c) 2017 Plop Grizzly, Jeron Lau <jeron.lau@plopgrizzly.com>       #
# Licensed under the MIT LICENSE                                               #
#                                                                              #
# src/lang/en/names.toml                                                       #
#    English names                                                             #

adam = "Adam"
adolph = "Adolph"
adrien = "Adrien"
allen = { common = "Allen", other = "Alan" }
albert = "Albert"
alexander = { common = "Alexander", nickname = "Alex" }
alfred = "Alfred"
alphonso = "Alphonso"
andrew = { common = "Andrew", nickname = "Drew" }
anthony = { common = "Anthony", nickname = "Tony" }
arthur = "Arthur"
bartholomew = "Bartholomew"
bartrand = "Bartrand"
benedict = "Benedict"
bernard = "Bernard"
charles = { common = "Charles", other = "Karl" }
caesar = "Caesar"
cyrus = "Cyrus"
clement = "Clement"
conrad = "Conrad"
cornelius = "Cornelius"
christopher = { common = "Cristopher", other = "Christian" }
daniel = { common = "Daniel", nickname = "Dan" }
david = { common = "David", nickname = "Dave" }
dominic = "Dominic"
edmund = "Edmund"
edward = { common = "Edward", nickname = ["Ed", "Eddy"] }
henry = { common = "Henry" }
ernest = "Ernest"
stephan = { common = ["Stephan", "Stephen"], other = "Steven", nickname = "Steve" }
eugene = "Eugene"
frederick = "Frederick"
philip = { common = "Philip", nickname = "Phil" }
ferdinand = "Ferdinand"
frank = "Frank"
gabriel = "Gabriel"
geoffrey = = { common = "Geoffrey", nickname = "Jeff" }
gerald = "Gerald"
gilbert = "Gilbert"
gregory = { common = "Gregory", nickname = "Greg" }
walter = { common = "Walter", nickname = "Walt" }
william = { common = "William", nickname = "Will" }
harold = "Harold"
herbert = "Hebert"
horace = "Horace"
hubert = "Hubert"
hugo = { common = "Hugh", other = "Hugo" }
angel = "Angel"
dingo = "Dingo" # No english equivalent ?
gonzalo = "Gonzalo" # No english equivalent ?
humphrey = "Humphrey"
alphonso = "Alphonso"
james = { common = "James", other = "Jim", nickname = "Jimmy" }
george = "George"
joseph = { common = "Joseph", nickname = ["Joe", "Joey"] }
john = { common = "Jonathan", other = "John", nickname = "Johny" }
julius = "Julius"
leon = { common = "Leo", other = ["Leon", "Lee"] }
leonard = "Leonard"
leopold = "Leopoldo"
lucas = { common = "Lucas", nickname = "Luke" }
louis = { common = ["Louis", "Lewis"], nickname = "Louie" }
manuel = "Manuel" # No english equivalent ?
marcel = "Marcel"
mark = "Mark"
mario = "Mario"
martin = "Martin"
matthew = { common = "Matthew", nickname = "Matt" }
michael = { common = "Michael", nickname = "Mike" }
nathan = { common = "Nathan", nickname = "Nate" }
oliver = "Oliver"
oscar = "Oscar"
osmond = "Osmond"
paul = "Paul"
frank = "Frank"
patrick = { common = "Patrick, nickname = "Pat" }
peter = { common = "Peter", nickname = "Pete" }
rafael = "Rafael"
raymond = { common = "Raymond", nickname = "Ray" }
raul = "Raul" # No english equivalent ?
richard = { common = "Richard", nickname = "Rich" }
robert = { common = "Robert", nickname = ["Rob", "Bob"] }
rudolph = "Rudolph"
roland = "Roland"
rueben = "Rueben"
rupert = "Rupert"
silvan = "Silvan"
silvester = "Silvester"
theodore = "Theodore"
timothy = { common = "Timothy", nickname = "Tim" }
thomas = { common = "Thomas", nikname = "Tom" }
vincent = common = "Vicent"
lorenzo = "Lorenzo" # No english equivalent ?
nicholas = { common = "Nicholas", nickname = "Nick" }
salvador = "Salvador" # No english equivalent ?
samuel = { common = "Samuel", nickname = "Sam" }
sancho = "Sancho" # No english equivalent ?
santiago = "Santiago" # No english equivalent ?
sergio = "Sergio" # No english equivalent ?
adele = "Adele"
dawn = "Dawn"
alice = "Alice"
amy = "Amy"
ann = "Ann"
beatrice = "beatrice"
bridget = "Bridget"
camilla = { common = "Camilla", other = "Camille" }
carla = "Carla"
charlotte = "Carlotte"
caroline = "Caroline"
carmen = "Carmen" # No english equivalent ?
katherine = { common = "Katherine", nickname = "Kate" }
constance = "Constance"
christina = "Christina"
dorothy = "Dorothy"
helen = { common = "Helen", other = ["Ellen", "Ella"] }
elsie = "Elsie"
emily = "Emily"
grace = "Grace"
henrietta = "Henrietta"
estelle = "Estelle"
esther = { common = "Esther", other = "Hester" }
eugenia = "Eugenia" # No english equivalent ?
eva = { common = "evelyn", nickname = "Eve" }
philippa = "Philippa"
florence = "Florence"
frances = "Frances"
gertrude = "Gertrude"
gloria = "Gloria"
guadalupe = "Guadalupe" # No english equivalent ?
wilhelmina = "Wilhelmina"
agnes = { common = "Agnes", other = "Inez" }
elizabeth = { common = "Elizabeth", other = "Isabel" }
josephine = { common = "Josefa", other = "josefina" }
jane = { common "Jane", other = ["Jean", "Joan"] }
juliet = { common = "Juliet", other = "Julie" }
laura = { common = "Laura", other = ["Laurie", "Laurel"] }
eleanor = "ELeanor"
leticia = "Leticia" # No english equivalent ?
dolores = { common = "Dolores", nickname = "Lola" } # No english equivalent ?
lucy = "Lucy"
louise = "Louise"
emma = "Emma"
margaret = "Margaret"
mary = "Mary"
marian = "Marian"
martha = "Martha"
hortense = "Hortense"
patricia = "Patricia"
pauline = "Pauline"
pearl = "Pearl"
pilar = "Pilar" # No english equivalent ?
ramona = "Ramona" # No english equivalent ?
rachel = "Rachel"
rose = "Rose"
sophie = "Sophie"
susan = { common = "Susan", nickname = "Sue" }
theodora = "Theodora"
therese = "Therese"
victoria = "Victoria"
virginia = "Virginia"
diana = "Diana"
sarah = ["Sarah", "Sara"]
amalia = "Amalia" # No english equivalent ?
gabriela = { common = "Gabriela", nickname = "Gabi" } # No english equivalent ?
julia = "Julia"
marcela = "Marcela" # No english equivalent ?
maricarmen = "Maricarmen" # No english equivalent ?
mercedes = "Mercedes" # No english equivalent ?
monica = "Monica" # No english equivalent ?
rebecca = "Rebecca"
yolanda = { common = "Yolanda", nickname = "Yoli" } # No english equivalent ?
tina = "Tina" # No english equivalent ?
